apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: ClusterIP
  ports:
    - name: slave
      port: 50000
      targetPort: 50000
      protocol: TCP
    - name: master
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: jenkins